//Usuario
export const MODIFICAR_USUARIO='MODIFICAR_USUARIO';
export const OBTENER_USUARIOS= 'OBTENER_USUARIOS';
export const OBTENER_USUARIO_BY_ID= 'OBTENER_USUARIO_BY_ID';
export const SET_USER_FILTER= 'SET_USER_FILTER';

//Registro
export const OBTENER_REGISTRO_BY_CREATOR='OBTENER_REGISTRO_BY_CREATOR';
export const REGISTRAR_REGISTRO='REGISTRAR_REGISTRO';
export const ELIMINAR_REGISTRO='ELIMINAR_REGISTRO';
export const OBTENER_REGISTROS='OBTENER_REGISTROS';
export const OBTENER_REGISTRO_BY_ID='OBTENER_REGISTRO_BY_ID';
export const ESTABLECER_UBICACION='ESTABLECER_UBICACION'
export const RESTABLECER_UBICACION='RESTABLECER_UBICACION'
export const ESTABLECER_ACCION='ESTABLECER_ACCION'
export const MODIFICAR_REGISTRO='MODIFICAR_REGISTRO'
export const AÑADIR_REGISTRO='AÑADIR_REGISTRO'


//Trabajador
export const OBTENER_TRABAJADOR_BY_CREATOR='OBTENER_TRABAJADOR_BY_CREATOR';
export const REGISTRAR_TRABAJADOR='REGISTRAR_TRABAJADOR';
export const ELIMINAR_TRABAJADOR='ELIMINAR_TRABAJADOR';
export const OBTENER_TRABAJADORES='OBTENER_TRABAJADORES';
export const OBTENER_TRABAJADOR_BY_ID='OBTENER_TRABAJADOR_BY_ID';
export const MODIFICAR_TRABAJADOR='MODIFICAR_TRABAJADOR'


//Auth
export const REGISTRO_EXITOSO= 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR= 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO= 'OBTENER_USUARIO';
export const CERRAR_SESION= 'CERRAR_SESION';
export const ELIMINAR_MENSAJE= 'ELIMINAR_MENSAJE';

//alertas
export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';

//busqueda
export const OBTENER_BUSQUEDA= 'OBTENER_BUSQUEDA';

//Carro
export const AÑADIR_CARRO= 'AÑADIR_CARRO';
export const ELIMINAR_CARRO= 'ELIMINAR_CARRO';
export const OBTENER_CARRO= 'OBTENER_CARRO';
export const MODIFICAR_PRODUCTO_CARRO= 'MODIFICAR_PRODUCTO_CARRO';


